bf16: true
cutoff_len: 2048
dataset: influence_identity,influence_demo_train
dataset_dir: data
do_train: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 2
learning_rate: 0.0001
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: q_proj,v_proj
loraplus_lr_ratio: 8
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: ./Qwen2.5-7B-Instruct
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/Custom/lora/train_2024-12-08-12-17-11
packing: false
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
warmup_steps: 0
